[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-os.json"
rustflags = ["-Cforce-unwind-tables"]

[profile.release-with-debug]
inherits = "release"
debug = true