[toolchain]
# When changing nightly version, make sure to change kernel/.vscode/launch.sh along with it
channel = "nightly-2023-06-20"
components = [ "rustfmt", "rustc-dev", "rust-src", "llvm-tools" ]
targets = [ "x64_64-unknown-linux-gnu" ]
profile = "minimal"