[toolchain]
# When changing nightly version, make sure to change kernel/.vscode/launch.sh along with it
channel = "nightly-2024-07-04"
components = [ "rustfmt", "rustc-dev", "rust-src", "llvm-tools", "clippy" ]
targets = [ "x64_64-unknown-linux-gnu" ]
profile = "minimal"